<a href="https://colab.research.google.com/github/rizzamhaqaryadestawan/TUGAS-Data-Wrangling/blob/main/Tugas%20data%20wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# BAGIAN A — Analisis Konseptual & Tata Kelola Data

## A.1 Pemetaan Kebutuhan Bisnis → Kebutuhan Teknis Data

| # | Pertanyaan Bisnis | Atribut Data | Tipe Data | Sumber Asal | Peran dalam Analisis |
|---|---|---|---|---|---|
| 1 | Total transaksi yang memakai kupon | `order_id` | string | CSV POS | Primary key transaksi; dasar hitung jumlah transaksi |
| | | `coupon_code` | string (nullable) | CSV POS | Penanda penggunaan kupon (tidak kosong = pakai kupon) |
| | | `order_date` | datetime64 | CSV POS | Membatasi periode kampanye akhir bulan; validasi tanggal |
| | | `gross_amount`, `discount_amount`, `total_amount` | integer (Rupiah) | CSV POS | Nilai transaksi, besar diskon, dan nilai bersih |
| | | `store_channel`, `payment_method` | string | CSV POS | Dimensi tambahan (kanal & metode bayar) |
| 2 | Profil loyalitas pelanggan pemakai kupon | `customer_id` | string | CSV POS (FK) & DB CRM (PK) | **Kunci join** POS ↔ CRM |
| | | `customer_name`, `city` | string | DB CRM | Identitas & demografi pelanggan |
| | | `membership_tier` | string / kategorikal (Bronze–Platinum) | DB CRM | Profil loyalitas |
| | | `join_date` | date → datetime64 | DB CRM | Lama keanggotaan |
| | | `is_active` | smallint (0/1) | DB CRM | Filter: hanya pelanggan aktif (`WHERE is_active = 1`) |
| 3 | Apakah pesanan sudah terkirim | `order_id` | string | REST API Logistik | **Kunci join** POS ↔ Logistik |
| | | `tracking_number` | string | REST API Logistik | Nomor resi |
| | | `delivery_status` | string / kategorikal | REST API Logistik | Status (DELIVERED, IN_TRANSIT, dst.) |
| | | `courier.name`, `courier.service` | string (nested → flat) | REST API Logistik | Mitra & layanan ekspedisi |
| | | `shipped_at`, `delivered_at` | datetime64 | REST API Logistik | Waktu kirim & tiba |

**Metrik turunan yang dihasilkan dari dataframe master:**
- Jumlah transaksi berkupon = `count(order_id)` dengan `coupon_code` tidak kosong
- Total nilai transaksi berkupon = `sum(total_amount)` dan total diskon = `sum(discount_amount)`
- Profil loyalitas = distribusi transaksi berkupon per `membership_tier` (dan `city`)
- Tingkat terkirim = persentase `delivery_status == 'DELIVERED'` dari transaksi berkupon

## A.2 Matriks RACI

**R** = Responsible (mengerjakan) · **A** = Accountable (penanggung jawab akhir, hanya satu per aktivitas) · **C** = Consulted · **I** = Informed

| Aktivitas | Head of Business Strategy (Data Owner) | Data Management Office / Data Steward | Tim Data Wrangling (Data Custodian / Engineer) | BI Analyst (Data User) |
|---|:---:|:---:|:---:|:---:|
| Menetapkan tujuan & KPI kampanye kupon | **A/R** | C | C | C |
| Menetapkan definisi data & standar kualitas (aturan bisnis) | **A** | **R** | C | C |
| Memberi izin akses ke sumber data (POS, CRM, API logistik) | **A** | **R** | C | I |
| Membangun pipeline ingestion & integrasi multi-sumber | I | C | **A/R** | C |
| Menyusun kamus data & menjalankan validasi otomatis (assert) | I | **A** | **R** | C |
| Menganalisis kinerja kampanye & menyusun laporan/dashboard | **A** | I | C | **R** |

**Catatan peran:** Head of Business Strategy memiliki data dan hasil akhirnya (Accountable atas keputusan bisnis). Data Steward menjaga definisi, standar, dan kualitas data. Tim Data Wrangling (Data Custodian) mengoperasikan pipeline dan penyimpanan teknis. BI Analyst adalah pengguna data yang mengolahnya menjadi insight.

---
# BAGIAN B — Komputasi Python & Data Ingestion Pipeline

## B.0 Import Library & Konfigurasi
Kredensial database dibaca dari *environment variable* `NEON_DATABASE_URL` agar password tidak tertulis di notebook / GitHub. Jika tidak di-set, isi nilai *placeholder* di bawah (jangan di-commit ke GitHub dengan password asli).

In [4]:
import os
import pandas as pd
import numpy as np
import requests
from sqlalchemy import create_engine, text

# ------------------------- KONFIGURASI -------------------------
CSV_PATH = "/content/drive/MyDrive/data w/transaksi_pos.csv"

# Connection string dari Neon (Dashboard -> Connect). Contoh format:
# postgresql://USER:PASSWORD@ep-xxxx.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
NEON_URL = os.getenv("NEON_DATABASE_URL",
                     "postgresql+psycopg2://neondb_owner:npg_bawA5rnvJKL2@ep-autumn-rain-b5trerr4-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require")

# Endpoint MockAPI.io (resource "deliveries")
API_URL = os.getenv("LOGISTIK_API_URL",
                    "https://6abdd79bc4d5ac5483011c32.mockapi.io/deliveries")

def to_sqlalchemy_url(url: str) -> str:
    """Neon memberi URL 'postgresql://'; SQLAlchemy butuh driver eksplisit (psycopg2)."""
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+psycopg2://", 1)
    return url

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
print("[OK] Library & konfigurasi siap.")

[OK] Library & konfigurasi siap.

## B.1 Ekstraksi Berkas File (CSV) — Divisi Kasir/POS
- `order_id` dan `customer_id` dipaksa bertipe **string** (`dtype`) agar angka nol di depan / format ID tidak rusak.
- `order_date` di-parse menjadi **datetime** (`parse_dates`).

In [5]:
print("[INFO] Mengimpor berkas transaksi POS...")
df_transaksi = pd.read_csv(
    CSV_PATH,
    dtype={"order_id": str, "customer_id": str},
    parse_dates=["order_date"],
)

print(f"[OK] {len(df_transaksi):,} baris, {df_transaksi.shape[1]} kolom dimuat.")
print(df_transaksi.dtypes)
df_transaksi.head()

[INFO] Mengimpor berkas transaksi POS...
[OK] 200 baris, 9 kolom dimuat.
order_id                   object
customer_id                object
order_date         datetime64[ns]
store_channel              object
payment_method             object
coupon_code                object
gross_amount                int64
discount_amount             int64
total_amount                int64
dtype: object

          order_id customer_id          order_date  store_channel payment_method coupon_code  gross_amount  discount_amount  total_amount
0  ORD-202609-0004       C0017 2026-09-01 09:56:00         Online           QRIS         NaN        715000                0        715000
1  ORD-202609-0127       C0035 2026-09-01 12:54:00   Toko Bandung          Debit         NaN        420000                0        420000
2  ORD-202609-0082       C0054 2026-09-01 16:26:00         Online       E-Wallet         NaN        285000                0        285000
3  ORD-202609-0106       C0004 2026-09-01 17:55:00  Toko Semarang       E-Wallet         NaN       1805000                0       1805000
4  ORD-202609-0002       C0056 2026-09-01 18:12:00         Online   Kartu Kredit         NaN       1070000                0       1070000

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## B.2 Koneksi & Kueri Database (SQL) — Divisi CRM / Membership
Koneksi ke PostgreSQL (Neon) menggunakan SQLAlchemy. Hanya pelanggan **aktif** (`WHERE is_active = 1`) yang diambil.

In [7]:
print("[INFO] Menghubungkan ke database CRM (Neon PostgreSQL)...")
engine = create_engine(to_sqlalchemy_url(NEON_URL))

query_crm = """
    SELECT customer_id, customer_name, membership_tier, city, join_date
    FROM customers
    WHERE is_active = 1
"""

with engine.connect() as conn:
    df_crm = pd.read_sql(text(query_crm), conn)

df_crm["customer_id"] = df_crm["customer_id"].astype(str)
df_crm["join_date"] = pd.to_datetime(df_crm["join_date"])

print(f"[OK] {len(df_crm):,} pelanggan aktif diambil dari CRM.")
df_crm.head()

[INFO] Menghubungkan ke database CRM (Neon PostgreSQL)...
[OK] 54 pelanggan aktif diambil dari CRM.

  customer_id  customer_name membership_tier        city  join_date
0       C0001   Dewi Santoso          Bronze    Semarang 2021-07-29
1       C0002    Maya Wijaya          Bronze     Jakarta 2022-04-22
2       C0003  Rudi Setiawan            Gold    Semarang 2024-12-07
3       C0004   Maya Nugroho          Bronze       Tegal 2021-01-14
4       C0005     Joko Utami          Bronze  Yogyakarta 2022-11-21

## B.3 Konsumsi REST API & Normalisasi JSON — Mitra Logistik
Request `GET` ke endpoint mock (MockAPI.io). Struktur JSON bersarang (`courier{}`, `destination{}`) diratakan dengan `pd.json_normalize()`. Parameter `sep="_"` membuat nama kolom hasil ratakan menjadi `courier_name`, `courier_service`, `destination_city`, dst.

In [8]:
print("[INFO] Menarik data pengiriman dari REST API...")
response = requests.get(API_URL, timeout=15)
response.raise_for_status()          # error jika status bukan 2xx

payload = response.json()
# Dukung dua bentuk respons: list langsung, atau {"results": [...]}
records = payload["results"] if isinstance(payload, dict) and "results" in payload else payload

# Contoh 1 record mentah (nested)
print("Contoh record mentah:")
print(records[0])

# Ratakan (flatten) JSON bersarang
df_logistik = pd.json_normalize(records, sep="_")

# Rapikan: ID jadi string, kolom waktu jadi datetime
df_logistik = df_logistik.rename(columns={"id": "delivery_id"})
df_logistik["order_id"] = df_logistik["order_id"].astype(str)
for col in ["shipped_at", "delivered_at"]:
    df_logistik[col] = pd.to_datetime(df_logistik[col], errors="coerce")

# Pengaman: satu order hanya boleh satu baris pengiriman (cegah duplikasi saat merge)
n_dup = df_logistik["order_id"].duplicated().sum()
if n_dup:
    print(f"[WARN] {n_dup} order_id duplikat di API -> dipertahankan record terakhir.")
    df_logistik = df_logistik.drop_duplicates(subset="order_id", keep="last")

print(f"[OK] {len(df_logistik):,} data pengiriman; kolom hasil flatten:")
print(list(df_logistik.columns))
df_logistik.head()

[INFO] Menarik data pengiriman dari REST API...
Contoh record mentah:
{'id': 1, 'order_id': 'ORD-202609-0004', 'tracking_number': 'J&T8025152555', 'delivery_status': 'DELIVERED', 'courier': {'name': 'J&T', 'service': 'EZ'}, 'destination': {'city': 'Medan', 'province': 'Indonesia'}, 'shipped_at': '2026-09-02T09:56:00', 'delivered_at': '2026-09-05T09:56:00', 'shipping_cost': 10000}
[OK] 53 data pengiriman; kolom hasil flatten:
['delivery_id', 'order_id', 'tracking_number', 'delivery_status', 'shipped_at', 'delivered_at', 'shipping_cost', 'courier_name', 'courier_service', 'destination_city', 'destination_province']

   delivery_id         order_id tracking_number delivery_status          shipped_at        delivered_at  shipping_cost courier_name courier_service destination_city destination_province
0            1  ORD-202609-0004   J&T8025152555       DELIVERED 2026-09-02 09:56:00 2026-09-05 09:56:00          10000          J&T              EZ            Medan            Indonesia
1            2  ORD-202609-0082   JNE8544878538       DELIVERED 2026-09-02 16:26:00 2026-09-03 16:26:00          31000          JNE             REG         Surabaya            Indonesia
2            3  ORD-202609-0002   JNE8281641403        RETURNED 2026-09-02 18:12:00                 NaT          17000          JNE             YES         Surabaya            Indonesia
3            4  ORD-202609-0197   J&T2260326267       DELIVERED 2026-09-04 09:53:00 2026-09-06 09:53:00          11000          J&T              EZ          Jakarta            Indonesia
4            5  ORD-202609-0075   SIC7328203808       PICKED_UP 2026-09-04 15:22:00                 NaT          21000      SiCepat            BEST          Jakarta            Indonesia

## B.4 Integrasi Data Multi-Sumber (Merging)

**Pilihan join dan alasan logis:**

1. **POS ⟕ CRM → `inner join` pada `customer_id`**
   Kebutuhan bisnis menanyakan *profil loyalitas pelanggan pemakai kupon*, sehingga hanya transaksi milik **member aktif** yang relevan. Query CRM sudah difilter `is_active = 1`, maka `inner join` otomatis menyaring transaksi dari pelanggan nonaktif / tidak terdaftar yang tidak punya profil loyalitas dan tidak dapat dianalisis.

2. **Hasil (1) ⟕ Logistik → `left join` pada `order_id`**
   Tabel POS adalah *sumber kebenaran* seluruh transaksi. Tidak semua pesanan punya data pengiriman (misalnya pembelian di toko fisik, atau pesanan yang belum diserahkan ke ekspedisi). Dengan `left join`, **tidak ada transaksi yang hilang**; pesanan tanpa data pengiriman muncul sebagai `NaN` sehingga menjawab langsung pertanyaan *"apakah pesanan sudah terkirim?"* (belum tercatat = belum terkirim). `inner join` di sini justru akan membuang transaksi yang belum dikirim dan membuat tingkat pengiriman tampak lebih baik dari kenyataan.

Parameter `validate` dipakai untuk memastikan relasi benar (*many-to-one*) sehingga merge tidak menggandakan baris.

In [9]:
print("[INFO] Melakukan integrasi data multi-sumber...")
n_awal = len(df_transaksi)

# 1) POS + CRM  -> inner join
df_master = df_transaksi.merge(df_crm, on="customer_id", how="inner", validate="many_to_one")
print(f"   Setelah join CRM (inner)    : {len(df_master):,} baris "
      f"({n_awal - len(df_master):,} transaksi dibuang: pelanggan nonaktif/tidak terdaftar)")

# 2) hasil + Logistik -> left join
df_master_analisis = df_master.merge(df_logistik, on="order_id", how="left", validate="one_to_one")
print(f"   Setelah join Logistik (left): {len(df_master_analisis):,} baris, "
      f"{df_master_analisis['tracking_number'].isna().sum():,} belum punya data pengiriman")

print(f"[OK] df_master_analisis: {df_master_analisis.shape[0]:,} baris x {df_master_analisis.shape[1]} kolom")
df_master_analisis.head()

[INFO] Melakukan integrasi data multi-sumber...
   Setelah join CRM (inner)    : 181 baris (19 transaksi dibuang: pelanggan nonaktif/tidak terdaftar)
   Setelah join Logistik (left): 181 baris, 132 belum punya data pengiriman
[OK] df_master_analisis: 181 baris x 23 kolom

,order_id,customer_id,order_date,store_channel,payment_method,coupon_code,gross_amount,discount_amount,total_amount,customer_name,membership_tier,city,join_date,delivery_id,tracking_number,delivery_status,shipped_at,delivered_at,shipping_cost,courier_name,courier_service,destination_city,destination_province
0,ORD-202609-0004,C0017,2026-09-01 09:56:00,Online,QRIS,NaN,715000,0,715000,Wati Hidayat,Bronze,Denpasar,2021-04-07,1.0,J&T8025152555,DELIVERED,2026-09-02 09:56:00,2026-09-05 09:56:00,10000.0,J&T,EZ,Medan,Indonesia
1,ORD-202609-0127,C0035,2026-09-01 12:54:00,Toko Bandung,Debit,NaN,420000,0,420000,Eko Hidayat,Bronze,Denpasar,2022-01-11,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
2,ORD-202609-0082,C0054,2026-09-01 16:26:00,Online,E-Wallet,NaN,285000,0,285000,Sri Pratama,Silver,Makassar,2021-08-18,2.0,JNE8544878538,DELIVERED,2026-09-02 16:26:00,2026-09-03 16:26:00,31000.0,JNE,REG,Surabaya,Indonesia
3,ORD-202609-0106,C0004,2026-09-01 17:55:00,Toko Semarang,E-Wallet,NaN,1805000,0,1805000,Maya Nugroho,Bronze,Tegal,2021-01-14,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
4,ORD-202609-0002,C0056,2026-09-01 18:12:00,Online,Kartu Kredit,NaN,1070000,0,1070000,Maya Pratama,Bronze,Jakarta,2021-03-23,3.0,JNE8281641403,RETURNED,2026-09-02 18:12:00,NaT,17000.0,JNE,YES,Surabaya,Indonesia

---
# BAGIAN C — Metadata, Kamus Data, & Validasi Aturan Bisnis

## C.1 Otomasi Kamus Data (Data Dictionary)
Fungsi berikut menghasilkan metadata setiap kolom: nama kolom, tipe data sistem (`dtype`), jumlah & persentase *missing value*, jumlah nilai unik, dan sampel nilai. Hasilnya disimpan ke `kamus_data_hasil.csv`.

In [10]:
def generate_data_dictionary(df: pd.DataFrame, n_sample: int = 3) -> pd.DataFrame:
    """Hasilkan ringkasan metadata (kamus data) dari sebuah DataFrame."""
    rows = []
    total = len(df)
    for col in df.columns:
        s = df[col]
        n_missing = int(s.isna().sum())
        sample = s.dropna().unique()[:n_sample]
        rows.append({
            "Nama Kolom": col,
            "Tipe Data (dtype)": str(s.dtype),
            "Jumlah Missing": n_missing,
            "Missing (%)": round(n_missing / total * 100, 2) if total else 0.0,
            "Jumlah Nilai Unik": int(s.nunique(dropna=True)),
            "Sampel Nilai": " | ".join(str(v) for v in sample) if len(sample) else "-",
        })
    return pd.DataFrame(rows)

kamus_df = generate_data_dictionary(df_master_analisis)
kamus_df.to_csv("kamus_data_hasil.csv", index=False, encoding="utf-8")
print("[INFO] Kamus data berhasil disimpan ke kamus_data_hasil.csv")
kamus_df

[INFO] Kamus data berhasil disimpan ke kamus_data_hasil.csv

              Nama Kolom Tipe Data (dtype)  Jumlah Missing  Missing (%)  Jumlah Nilai Unik                                       Sampel Nilai
0               order_id            object               0         0.00                181  ORD-202609-0004 | ORD-202609-0127 | ORD-202609...
1            customer_id            object               0         0.00                 52                              C0017 | C0035 | C0054
2             order_date    datetime64[ns]               0         0.00                181  2026-09-01 09:56:00 | 2026-09-01 12:54:00 | 20...
3          store_channel            object               0         0.00                  5              Online | Toko Bandung | Toko Semarang
4         payment_method            object               0         0.00                  5                            QRIS | Debit | E-Wallet
5            coupon_code            object             152        83.98                  3                 GAJIAN10 | AKHIRBULAN15 | DISKON25
6           gross_amount             int64               0         0.00                147                           715000 | 420000 | 285000
7        discount_amount             int64               0         0.00                 28                                0 | 247000 | 126000
8           total_amount             int64               0         0.00                153                           715000 | 420000 | 285000
9          customer_name            object               0         0.00                 45           Wati Hidayat | Eko Hidayat | Sri Pratama
10       membership_tier            object               0         0.00                  4                             Bronze | Silver | Gold
11                  city            object               0         0.00                 10                        Denpasar | Makassar | Tegal
12             join_date    datetime64[ns]               0         0.00                 51  2021-04-07 00:00:00 | 2022-01-11 00:00:00 | 20...
13           delivery_id           float64             132        72.93                 49                                    1.0 | 2.0 | 3.0
14       tracking_number            object             132        72.93                 49      J&T8025152555 | JNE8544878538 | JNE8281641403
15       delivery_status            object             132        72.93                  5                   DELIVERED | RETURNED | PICKED_UP
16            shipped_at    datetime64[ns]             132        72.93                 49  2026-09-02 09:56:00 | 2026-09-02 16:26:00 | 20...
17          delivered_at    datetime64[ns]             160        88.40                 21  2026-09-05 09:56:00 | 2026-09-03 16:26:00 | 20...
18         shipping_cost           float64             132        72.93                 24                        10000.0 | 31000.0 | 17000.0
19          courier_name            object             132        72.93                  4                                J&T | JNE | SiCepat
20       courier_service            object             132        72.93                  4                                     EZ | REG | YES
21      destination_city            object             132        72.93                 10                         Medan | Surabaya | Jakarta
22  destination_province            object             132        72.93                  1                                          Indonesia

## C.2 Validasi Kualitas & Integritas (Automated Assertions)
Tiga aturan wajib: (1) tidak ada duplikasi *primary key* (`order_id`), (2) `total_amount` tidak negatif, (3) tidak ada `order_date` di masa depan. Jika salah satu gagal, `AssertionError` akan menghentikan pipeline.

In [11]:
df = df_master_analisis
hari_ini = pd.Timestamp.now()

# 1) Primary key tidak boleh duplikat (dan tidak boleh kosong)
assert df["order_id"].notna().all(), "Fatal: ada order_id kosong!"
assert not df["order_id"].duplicated().any(), "Fatal: terdeteksi order_id duplikat!"
print("[PASS] Tidak ada duplikasi pada primary key (order_id).")

# 2) Nilai transaksi tidak boleh negatif
assert df["total_amount"].notna().all(), "Fatal: ada total_amount kosong!"
assert (df["total_amount"] >= 0).all(), "Fatal: ada nilai transaksi (total_amount) negatif!"
print("[PASS] Tidak ada total_amount bernilai negatif.")

# 3) Tanggal pesanan tidak boleh melebihi hari ini
assert (df["order_date"] <= hari_ini).all(), (
    f"Fatal: ada order_date melebihi hari ini ({hari_ini:%Y-%m-%d})!"
)
print(f"[PASS] Tidak ada order_date di masa depan (maks: {df['order_date'].max():%Y-%m-%d %H:%M}).")

print("\n[SUCCESS] Seluruh validasi data lulus!")

[PASS] Tidak ada duplikasi pada primary key (order_id).
[PASS] Tidak ada total_amount bernilai negatif.
[PASS] Tidak ada order_date di masa depan (maks: 2026-09-30 21:07).

[SUCCESS] Seluruh validasi data lulus!

---
# BAGIAN D — Ringkasan Jawaban Kebutuhan Bisnis
Menjawab tiga pertanyaan Head of Business Strategy dari `df_master_analisis`.

In [12]:
df_kupon = df_master_analisis[df_master_analisis["coupon_code"].notna()].copy()

# 1) Total transaksi yang memakai kupon
print("=== 1. TRANSAKSI BERKUPON ===")
print(f"Jumlah transaksi berkupon : {len(df_kupon):,} dari {len(df_master_analisis):,} "
      f"({len(df_kupon)/len(df_master_analisis):.1%})")
print(f"Total nilai bersih        : Rp {df_kupon['total_amount'].sum():,.0f}")
print(f"Total diskon diberikan    : Rp {df_kupon['discount_amount'].sum():,.0f}")
display(df_kupon.groupby("coupon_code").agg(
    jumlah_transaksi=("order_id", "count"),
    total_nilai=("total_amount", "sum"),
    total_diskon=("discount_amount", "sum"),
).sort_values("jumlah_transaksi", ascending=False))

# 2) Profil loyalitas pemakai kupon
print("\n=== 2. PROFIL LOYALITAS PEMAKAI KUPON ===")
urutan_tier = ["Bronze", "Silver", "Gold", "Platinum"]
profil = (df_kupon.groupby("membership_tier")
          .agg(jumlah_transaksi=("order_id", "count"),
               pelanggan_unik=("customer_id", "nunique"),
               total_nilai=("total_amount", "sum"))
          .reindex(urutan_tier).fillna(0).astype(int))
profil["persen_transaksi"] = (profil["jumlah_transaksi"] / profil["jumlah_transaksi"].sum() * 100).round(1)
display(profil)

# 3) Status pengiriman
print("\n=== 3. STATUS PENGIRIMAN PESANAN BERKUPON ===")
status = df_kupon["delivery_status"].fillna("BELUM TERCATAT DI EKSPEDISI")
tabel_status = status.value_counts().rename("jumlah").to_frame()
tabel_status["persen"] = (tabel_status["jumlah"] / tabel_status["jumlah"].sum() * 100).round(1)
display(tabel_status)
terkirim = (status == "DELIVERED").sum()
print(f"Pesanan berkupon yang sudah terkirim (DELIVERED): {terkirim} dari {len(df_kupon)} ({terkirim/len(df_kupon):.1%})")

=== 1. TRANSAKSI BERKUPON ===
Jumlah transaksi berkupon : 29 dari 181 (16.0%)
Total nilai bersih        : Rp 34,730,000
Total diskon diberikan    : Rp 4,415,000

              jumlah_transaksi  total_nilai  total_diskon
coupon_code
GAJIAN10                    22     26528000       2942000
AKHIRBULAN15                 6      8022000       1413000
DISKON25                     1       180000         60000

=== 2. PROFIL LOYALITAS PEMAKAI KUPON ===

                 jumlah_transaksi  pelanggan_unik  total_nilai  persen_transaksi
membership_tier
Bronze                         16              14     21628000              55.2
Silver                          4               2      3264000              13.8
Gold                            7               5      6620000              24.1
Platinum                        2               2      3218000               6.9

=== 3. STATUS PENGIRIMAN PESANAN BERKUPON ===

                             jumlah  persen
delivery_status
DELIVERED                        11    37.9
PICKED_UP                         7    24.1
IN_TRANSIT                        4    13.8
RETURNED                          3    10.3
BELUM TERCATAT DI EKSPEDISI       3    10.3
PENDING                           1     3.4

Pesanan berkupon yang sudah terkirim (DELIVERED): 11 dari 29 (37.9%)